"""Create manager permissions table

Revision ID: 4f65fb15c6d9
Revises: 9c63f3a6393c
Create Date: 2026-03-09 05:15:45.881570
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f65fb15c6d9'
down_revision: Union[str, None] = '9c63f3a6393c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_manage_users', sa.Boolean(), nullable=True),
    sa.Column('can_manage_courses', sa.Boolean(), nullable=True),
    sa.Column('can_manage_categories', sa.Boolean(), nullable=True),
    sa.Column('can_manage_applications', sa.Boolean(), nullable=True),
    sa.Column('can_manage_coupons', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_manager_permissions_id'), 'manager_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manager_permissions_id'), table_name='manager_permissions')
    op.drop_table('manager_permissions')
    # ### end Alembic commands ###
