"""Add placement stats table

Revision ID: 7b9b933a62a3
Revises: baa2debe09de
Create Date: 2026-03-11 14:04:16.979957
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b9b933a62a3'
down_revision: Union[str, None] = 'baa2debe09de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('highest_package', sa.String(length=50), nullable=False),
    sa.Column('average_package', sa.String(length=50), nullable=False),
    sa.Column('placement_percentage', sa.String(length=20), nullable=False),
    sa.Column('total_hiring_partners', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('placement_stats')
    # ### end Alembic commands ###
