"""Add Manager Permissions again

Revision ID: 9c63f3a6393c
Revises: f870dde8f736
Create Date: 2026-03-09 05:13:11.807294
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c63f3a6393c'
down_revision: Union[str, None] = 'f870dde8f736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
