"""create coupons table

Revision ID: e7d262831d73
Revises: 003_cv_url
Create Date: 2026-03-07 07:38:02.891603
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d262831d73'
down_revision: Union[str, None] = '003_cv_url'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.drop_index('ix_courses_category_id', table_name='courses')
    op.drop_index('ix_courses_teacher_id', table_name='courses')
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.drop_index('ix_enrollments_user_course', table_name='enrollments')
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.drop_index('ix_lessons_course_id', table_name='lessons')
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_progress_id'), 'progress', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.drop_index('ix_teacher_applications_status', table_name='teacher_applications')
    op.drop_index('ix_teacher_applications_user_id', table_name='teacher_applications')
    op.create_index(op.f('ix_teacher_applications_id'), 'teacher_applications', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_teacher_applications_id'), table_name='teacher_applications')
    op.create_index('ix_teacher_applications_user_id', 'teacher_applications', ['user_id'], unique=False)
    op.create_index('ix_teacher_applications_status', 'teacher_applications', ['status'], unique=False)
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_progress_id'), table_name='progress')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.create_index('ix_lessons_course_id', 'lessons', ['course_id'], unique=False)
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.create_index('ix_enrollments_user_course', 'enrollments', ['user_id', 'course_id'], unique=True)
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.create_index('ix_courses_teacher_id', 'courses', ['teacher_id'], unique=False)
    op.create_index('ix_courses_category_id', 'courses', ['category_id'], unique=False)
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    # ### end Alembic commands ###
